baseurl: "https://ameblo.github.io/a11y-guidelines"
title: "Ameblo Accessibility Guidelines"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layouts"
staticdir: "static"
publishdir: "public"
uglyUrls: false
metaDataFormat: "yaml"
permalinks:
  post: "/:title"
