version: 2
jobs:
  test:
    working_directory: ~/a11y-guidelines
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-cache-{{ .Branch }}
            - node-cache-master
            - node-cache-
      - run: npm install
      - run: npm run test
      - save_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules
  audit:
    working_directory: ~/a11y-guidelines
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: curl -OL https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz
      - run: tar fxz hugo_0.55.6_Linux-64bit.tar.gz hugo
      - run: sudo mv hugo /usr/local/bin/hugo
      - restore_cache:
          keys:
            - node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-cache-{{ .Branch }}
            - node-cache-master
            - node-cache-
      - run: npm install
      - run: npm run build
      - run: npx -p @lhci/cli -c 'lhci autorun'
workflows:
  version: 2
  build_flow:
    jobs:
      - test
      - audit
