version: 2
jobs:
  test:
    working_directory: ~/a11y-guidelines
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-cache-{{ .Branch }}
            - node-cache-master
            - node-cache-
      - run: npm install
      - run: npm run test
      - save_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules
workflows:
  version: 2
  build_flow:
    jobs:
      - test
